name: employee-burnout-prediction
description: Employee Burnout Prediction Model
cmd: >
  python3 main.py --input ${DATA}
env:
  python: auto
inputs:
  - dataset.csv: DATA
outputs:
  - burnout_model_state_dict.save
  - burnout_optimizer_state_dict.save
cloud-instance-type: g1.1
